routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '/panel', 'namespace' => 'Panel', 'as' => 'panel.'], function () {
    Route::group(['prefix' => '/message', 'as' => 'message.'], function () {
        Route::get('/', 'MessageController@index')->name('index');
        Route::get('/edit/{message}', 'MessageController@edit')->name('edit');
        Route::post('/edit/{message}', 'MessageController@update')->name('update');
        Route::get('/delete/{message}', 'MessageController@delete')->name('delete');
    });
});

app/Models/Message.php
<?php

namespace App\Models;

use DateTime;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Message
 * @package App\Models
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $message
 * @property DateTime $created_at
 * @property DateTime $updated_at
 */
class Message extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'email', 'phone', 'message'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];
}

app/Http/Controllers/API/V1/MessageController.php
<?php

namespace App\Http\Controllers\API\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\Message\MessageSaveRequest;
use App\Http\Resources\MessageResource;
use App\Models\Message;
use Exception;

class MessageController extends Controller
{
    public function index()
    {
        $messages = Message::query()->paginate();

        return MessageResource::collection($messages);
    }

    public function show(Message $message)
    {
        return MessageResource::make($message);
    }

    public function store(MessageSaveRequest $request)
    {
        $message = Message::query()->create($request->validated());

        return MessageResource::make($message);
    }

    public function update(MessageSaveRequest $request, Message $message)
    {
        $message->update($request->validated());

        return MessageResource::make($message);
    }

    public function destroy(Message $message)
    {
        $clone = clone $message;
        try {
            $message->delete();
        } catch (Exception $e) {
        }

        return MessageResource::make($clone);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Panel/MessageController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Http\Requests\Message\MessageSaveRequest;
use App\Models\Message;
use Exception;

class MessageController extends Controller
{
    public function index()
    {
        $messages = Message::query()->paginate(5);

        return view('panel.message.index', compact('messages'));
    }

    public function edit(Message $message)
    {
        return view('panel.message.form', compact('message'));
    }

    public function update(MessageSaveRequest $request, Message $message)
    {
        $message->update($request->validated());

        return redirect()->route('panel.message.edit', ['message' => $message->id, 'readOnly' => '1']);
    }

    public function delete(Message $message)
    {
        try {
            $message->delete();
        } catch (Exception $e) {

        }

        return redirect()->route('panel.message.index');
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{env('APP_NAME')}} @yield('page_title')</title>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-200 p-4 flex flex-col items-center">
@yield('content')
</body>
</html>

resources/views/panel/message/form.blade.php
@extends('layout')
@section('content')
    <div class="container">
        <div class="flex flex-col shadow bg-white border border-gray-300 rounded" style="min-height: 300px">
            <form method="post" action="{{route('panel.message.update', ['message' => $message->id])}}"
                  class="flex flex-col w-full p-4">
                {{csrf_field()}}
                <div class="flex flex-row flex-wrap w-full mb-2">
                    <label for="name" class="mr-2" style="flex-basis: 200px">Name</label>
                    <input type="text" class="flex-1 rounded border border-gray-200 p-2" name="name"
                           {{request()->query('readOnly') == '1' ? 'readonly' : ''}}
                           value="{{old('name', $message->name)}}" id="name"/>
                    @error('name')
                    <div
                        class="flex flex-col border rounded border-red-500 bg-red-200 text-red-700 font-bold w-full my-2 p-2">
                        {{$message}}
                    </div>
                    @enderror
                </div>

                <div class="flex flex-row flex-wrap w-full mb-2">
                    <label for="email" class="mr-2" style="flex-basis: 200px">Email</label>
                    <input type="email" class="flex-1 rounded border border-gray-200 p-2" name="email"
                           {{request()->query('readOnly') == '1' ? 'readonly' : ''}}
                           value="{{old('email', $message->email)}}" id="email"/>
                    @error('email')
                    <div
                        class="flex flex-col border rounded border-red-500 bg-red-200 text-red-700 font-bold w-full my-2 p-2">
                        {{$message}}
                    </div>
                    @enderror
                </div>

                <div class="flex flex-row flex-wrap w-full mb-2">
                    <label for="phone" class="mr-2" style="flex-basis: 200px">Phone</label>
                    <input type="tel" class="flex-1 rounded border border-gray-200 p-2" name="phone" id="phone"
                           {{request()->query('readOnly') == '1' ? 'readonly' : ''}}
                           value="{{old('phone', $message->phone)}}"/>
                    @error('phone')
                    <div
                        class="flex flex-col border rounded border-red-500 bg-red-200 text-red-700 font-bold w-full my-2 p-2">
                        {{$message}}
                    </div>
                    @enderror
                </div>

                <div class="flex flex-row flex-wrap w-full mb-2">
                    <label for="message" class="mr-2" style="flex-basis: 200px">Message</label>
                    <textarea id="message" name="message" {{request()->query('readOnly') == '1' ? 'readonly' : ''}}
                    class="flex-1 rounded border border-gray-200 p-2">{{old('message', $message->message)}}</textarea>
                    @error('message')
                    <div
                        class="flex flex-col border rounded border-red-500 bg-red-200 text-red-700 font-bold w-full my-2 p-2">
                        {{$message}}
                    </div>
                    @enderror
                </div>

                @if(request()->query('readOnly') != '1')
                    <div class="flex flex-row w-full mb-2">
                        <button type="submit"
                                class="bg-blue-500 hover:bg-blue-400 text-white px-4 py-2 rounded border border-blue-300">
                            Submit
                        </button>
                    </div>
                @endif
            </form>
        </div>
    </div>
@endsection

resources/views/panel/message/index.blade.php
@extends('layout')
@section('content')
    <div class="container">
        <div class="flex flex-col shadow bg-white border border-gray-300 rounded" style="min-height: 300px">
            <table class="table w-full mb-2">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Operations</th>
                </tr>
                </thead>
                <tbody>
                @foreach($messages as $message)
                    <tr>
                        <td>{{$message->id}}</td>
                        <td>{{$message->name}}</td>
                        <td>{{$message->phone}}</td>
                        <td width="160">
                            <div class="flex flex-row w-full">
                                <a href="{{route('panel.message.delete', ['message' => $message->id])}}"
                                   class="px-4 py-2 mr-2 bg-red-500 hover:bg-red-400 text-white outline-none border border-red-300">
                                    Delete
                                </a>
                                <a href="{{route('panel.message.edit', ['message' => $message->id])}}"
                                   class="px-4 py-2 mr-2 bg-orange-500 hover:bg-orange-400 text-white outline-none border border-orange-300">
                                    Edit
                                </a>
                                <a href="{{route('panel.message.edit',['message' => $message->id, 'readOnly' => '1'])}}"
                                   class="px-4 py-2 mr-2 bg-blue-500 hover:bg-blue-400 text-white outline-none border border-blue-300">
                                    View
                                </a>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{$messages->links()}}
        </div>
    </div>
@endsection